'use client';

import React, { useState } from 'react';

interface Product {
  id: number;
  icon: string;
  title: string;
  price: string;
  priceSubtext: string;
  description: string;
}

interface Feature {
  id: number;
  title: string;
  description: string;
}

interface Stat {
  id: number;
  number: string;
  description: string;
}

interface FooterSection {
  title: string;
  links: string[];
}

export default function SquareLanding() {
  const [hoveredProduct, setHoveredProduct] = useState<number | null>(null);

  const products: Product[] = [
    {
      id: 1,
      icon: '📱',
      title: 'The sleek, dual-screen system',
      price: '$799',
      priceSubtext: 'or $39/mo. over 24 months',
      description: 'Advanced POS system with dual displays for maximum efficiency in any business environment.',
    },
    {
      id: 2,
      icon: '🏪',
      title: 'The POS that moves with you',
      price: '$399',
      priceSubtext: 'or $37/mo. over 12 months',
      description: 'Portable and powerful POS system designed for businesses on the go.',
    },
    {
      id: 3,
      icon: '🧾',
      title: 'The receipt-printing POS',
      price: '$299',
      priceSubtext: 'or $27/mo. over 12 months',
      description: 'Reliable point of sale system with integrated receipt printing capabilities.',
    },
    {
      id: 4,
      icon: '📲',
      title: 'The intuitive, swiveling iPad POS',
      price: '$149',
      priceSubtext: 'or $14/mo. over 12 months',
      description: 'Flexible iPad-based POS system with intuitive interface for quick transactions.',
    },
  ];

  const features: Feature[] = [
    {
      id: 1,
      title: '💳 Take payments',
      description: 'Sell anything in person and online with a point of sale platform that works for whatever you sell.',
    },
    {
      id: 2,
      title: '👥 Manage your team',
      description: 'Run payroll, schedule shifts, and take care of admin — so your team can focus on performing their best.',
    },
    {
      id: 3,
      title: '📈 Grow your customer base',
      description: 'Set up the right marketing campaigns and loyalty program to welcome new customers and keep them coming back.',
    },
    {
      id: 4,
      title: '💰 Control your cash flow',
      description: 'Bring your revenue under one roof. Instantly access your funds and get quicker access to loans.',
    },
    {
      id: 5,
      title: '🔌 Connect your apps',
      description: 'Square partners with hundreds of apps so you can manage your entire business without jumping between platforms.',
    },
    {
      id: 6,
      title: '🤖 Square AI',
      description: 'Ask Square AI anything about your business to get immediate insights and make smart decisions, fast.',
    },
  ];

  const stats: Stat[] = [
    {
      id: 1,
      number: '500M+',
      description: 'food and beverage sellers using Square globally',
    },
    {
      id: 2,
      number: '$2T+',
      description: 'generated by retailers using Square annually',
    },
    {
      id: 3,
      number: '100M+',
      description: 'appointments booked through Square every month',
    },
    {
      id: 4,
      number: '$1.5B+',
      description: 'paid with invoices globally',
    },
  ];

  const footerSections: FooterSection[] = [
    {
      title: 'Products',
      links: ['Point of Sale', 'Payments', 'Invoicing', 'Payroll'],
    },
    {
      title: 'Solutions',
      links: ['Restaurants', 'Retail', 'Services', 'Online'],
    },
    {
      title: 'Company',
      links: ['About', 'Careers', 'Press', 'Investors'],
    },
    {
      title: 'Support',
      links: ['Help Center', 'Community', 'Contact Us', 'Status'],
    },
  ];

  return (
    <div className="min-h-screen bg-white">
      <style>{`
        :root {
          --color-primary: #1f2937;
          --color-secondary: #6366f1;
          --color-accent: #0ea5e9;
          --color-text: #1f2937;
          --color-text-light: #6b7280;
          --color-bg: #ffffff;
          --color-border: #e5e7eb;
          --spacing-sm: 8px;
          --spacing-md: 16px;
          --spacing-lg: 24px;
          --spacing-xl: 32px;
          --spacing-2xl: 48px;
          --spacing-3xl: 64px;
          --border-radius: 8px;
          --transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
        }

        * {
          margin: 0;
          padding: 0;
          box-sizing: border-box;
        }

        html {
          scroll-behavior: smooth;
        }

        body {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', sans-serif;
          color: var(--color-text);
          background-color: var(--color-bg);
          line-height: 1.6;
        }

        /* Header */
        header {
          position: fixed;
          top: 0;
          left: 0;
          right: 0;
          background: rgba(255, 255, 255, 0.95);
          backdrop-filter: blur(10px);
          z-index: 1000;
          border-bottom: 1px solid var(--color-border);
        }

        .header-container {
          max-width: 1400px;
          margin: 0 auto;
          padding: var(--spacing-md) var(--spacing-lg);
          display: flex;
          justify-content: space-between;
          align-items: center;
        }

        .logo {
          font-size: 24px;
          font-weight: 700;
          color: var(--color-primary);
          text-decoration: none;
          letter-spacing: -0.5px;
        }

        nav {
          display: flex;
          gap: var(--spacing-2xl);
          align-items: center;
        }

        nav a {
          color: var(--color-text);
          text-decoration: none;
          font-size: 14px;
          font-weight: 500;
          transition: var(--transition);
        }

        nav a:hover {
          color: var(--color-secondary);
        }

        .btn {
          padding: 10px 24px;
          border-radius: var(--border-radius);
          border: none;
          font-weight: 600;
          font-size: 14px;
          cursor: pointer;
          transition: var(--transition);
          text-decoration: none;
          display: inline-block;
        }

        .btn-primary {
          background-color: var(--color-secondary);
          color: white;
        }

        .btn-primary:hover {
          background-color: #4f46e5;
          transform: translateY(-2px);
          box-shadow: 0 10px 20px rgba(99, 102, 241, 0.2);
        }

        .btn-secondary {
          background-color: transparent;
          color: var(--color-secondary);
          border: 2px solid var(--color-secondary);
        }

        .btn-secondary:hover {
          background-color: rgba(99, 102, 241, 0.1);
        }

        /* Hero Section */
        .hero {
          margin-top: 60px;
          position: relative;
          height: 100vh;
          display: flex;
          align-items: center;
          justify-content: center;
          overflow: hidden;
        }

        .hero-video {
          position: absolute;
          top: 0;
          left: 0;
          width: 100%;
          height: 100%;
          object-fit: cover;
          z-index: 1;
        }

        .hero-overlay {
          position: absolute;
          top: 0;
          left: 0;
          width: 100%;
          height: 100%;
          background: linear-gradient(135deg, rgba(31, 41, 55, 0.4) 0%, rgba(31, 41, 55, 0.2) 100%);
          z-index: 2;
        }

        .hero-content {
          position: relative;
          z-index: 3;
          text-align: center;
          color: white;
          max-width: 800px;
          padding: var(--spacing-lg);
        }

        .hero h1 {
          font-size: 56px;
          font-weight: 700;
          margin-bottom: var(--spacing-lg);
          line-height: 1.2;
          letter-spacing: -1px;
        }

        .hero p {
          font-size: 20px;
          margin-bottom: var(--spacing-2xl);
          opacity: 0.95;
          font-weight: 300;
        }

        .hero-buttons {
          display: flex;
          gap: var(--spacing-md);
          justify-content: center;
          flex-wrap: wrap;
        }

        .btn-light {
          background-color: white;
          color: var(--color-secondary);
          padding: 12px 32px;
          font-weight: 600;
        }

        .btn-light:hover {
          background-color: #f3f4f6;
          transform: translateY(-2px);
          box-shadow: 0 10px 25px rgba(0, 0, 0, 0.15);
        }

        /* Section Base */
        section {
          padding: var(--spacing-3xl) var(--spacing-lg);
        }

        .section-container {
          max-width: 1400px;
          margin: 0 auto;
        }

        .section-header {
          text-align: center;
          margin-bottom: var(--spacing-3xl);
        }

        .section-header h2 {
          font-size: 44px;
          font-weight: 700;
          margin-bottom: var(--spacing-md);
          line-height: 1.2;
        }

        .section-header p {
          font-size: 18px;
          color: var(--color-text-light);
          max-width: 600px;
          margin: 0 auto;
        }

        /* Products Section */
        .products {
          background-color: #f9fafb;
        }

        .products-grid {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
          gap: var(--spacing-2xl);
        }

        .product-card {
          background: white;
          padding: var(--spacing-2xl);
          border-radius: 12px;
          border: 1px solid var(--color-border);
          transition: var(--transition);
        }

        .product-card:hover {
          transform: translateY(-8px);
          box-shadow: 0 20px 40px rgba(0, 0, 0, 0.1);
        }

        .product-icon {
          font-size: 40px;
          margin-bottom: var(--spacing-md);
        }

        .product-card h3 {
          font-size: 20px;
          font-weight: 600;
          margin-bottom: var(--spacing-md);
        }

        .product-card p {
          color: var(--color-text-light);
          font-size: 15px;
          line-height: 1.7;
          margin-bottom: var(--spacing-md);
        }

        .price {
          font-size: 24px;
          font-weight: 700;
          color: var(--color-secondary);
          margin-bottom: var(--spacing-md);
        }

        .price-subtext {
          color: var(--color-text-light);
          font-size: 13px;
        }

        /* Features Section */
        .features {
          background-color: white;
        }

        .features-grid {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
          gap: var(--spacing-2xl);
        }

        .feature-card {
          padding: var(--spacing-2xl);
          border-radius: 12px;
          background: linear-gradient(135deg, #f0f9ff 0%, #f5f3ff 100%);
          border: 1px solid var(--color-border);
        }

        .feature-card h3 {
          font-size: 20px;
          font-weight: 600;
          margin-bottom: var(--spacing-md);
          color: var(--color-primary);
        }

        .feature-card p {
          color: var(--color-text-light);
          line-height: 1.7;
        }

        /* Stats Section */
        .stats {
          background: linear-gradient(135deg, var(--color-primary) 0%, #374151 100%);
          color: white;
        }

        .stats-grid {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
          gap: var(--spacing-3xl);
        }

        .stat-item h4 {
          font-size: 36px;
          font-weight: 700;
          margin-bottom: var(--spacing-sm);
        }

        .stat-item p {
          font-size: 16px;
          opacity: 0.95;
          font-weight: 300;
        }

        /* CTA Section */
        .cta {
          background: linear-gradient(135deg, var(--color-secondary) 0%, #4f46e5 100%);
          color: white;
          text-align: center;
        }

        .cta h2 {
          font-size: 44px;
          font-weight: 700;
          margin-bottom: var(--spacing-lg);
        }

        .cta p {
          font-size: 18px;
          margin-bottom: var(--spacing-2xl);
          opacity: 0.95;
        }

        /* Footer */
        footer {
          background-color: var(--color-primary);
          color: white;
          padding: var(--spacing-3xl) var(--spacing-lg);
        }

        .footer-content {
          max-width: 1400px;
          margin: 0 auto;
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
          gap: var(--spacing-2xl);
          margin-bottom: var(--spacing-2xl);
        }

        .footer-section h4 {
          font-weight: 600;
          margin-bottom: var(--spacing-md);
        }

        .footer-section a {
          color: rgba(255, 255, 255, 0.8);
          text-decoration: none;
          font-size: 14px;
          display: block;
          margin-bottom: var(--spacing-sm);
          transition: var(--transition);
        }

        .footer-section a:hover {
          color: white;
        }

        .footer-bottom {
          text-align: center;
          padding-top: var(--spacing-2xl);
          border-top: 1px solid rgba(255, 255, 255, 0.1);
          font-size: 14px;
          opacity: 0.8;
        }

        /* Responsive */
        @media (max-width: 768px) {
          .header-container {
            padding: var(--spacing-sm) var(--spacing-md);
          }

          nav {
            display: none;
          }

          .hero {
            margin-top: 50px;
            height: 80vh;
          }

          .hero h1 {
            font-size: 36px;
          }

          .hero p {
            font-size: 16px;
          }

          .section-header h2 {
            font-size: 32px;
          }

          .products-grid,
          .features-grid,
          .stats-grid {
            grid-template-columns: 1fr;
          }

          .hero-buttons {
            flex-direction: column;
          }

          .btn {
            width: 100%;
          }
        }
      `}</style>

      {/* Header */}
      <header>
        <div className="header-container">
          <a href="#" className="logo">Square</a>
          <nav>
            <a href="#products">Products</a>
            <a href="#features">Features</a>
            <a href="#pricing">Pricing</a>
            <a href="#about">About</a>
            <button className="btn btn-primary">Get Started</button>
          </nav>
        </div>
      </header>

      {/* Hero Section */}
      <section className="hero">
        <video className="hero-video" autoPlay muted loop playsInline>
          <source src="https://pw-assets-production-c.squarecdn.com/video/5mObdhW0r5D0lyp3iVJFA6/b4d81931-7cfa-4402-bb41-efc4126e3f95-en-ee526a6b-3ca3-4ae5-9bc2-be60cb21229f-en-Homepage_Edit-updated.webm" type="video/webm" />
          Your browser does not support the video tag.
        </video>
        <div className="hero-overlay"></div>
        <div className="hero-content">
          <h1>Power your entire business</h1>
          <p>Everything you need to run your business in one place. From payments to payroll, Square has you covered.</p>
          <div className="hero-buttons">
            <button className="btn btn-light">Start Free Trial</button>
            <button className="btn btn-secondary" style={{ color: 'white', borderColor: 'white' }}>
              Watch Demo
            </button>
          </div>
        </div>
      </section>

      {/* Products Section */}
      <section className="products" id="products">
        <div className="section-container">
          <div className="section-header">
            <h2>Smooth checkout, every time</h2>
            <p>Choose from a range of sleek options for however you do business. All equally easy to use.</p>
          </div>
          <div className="products-grid">
            {products.map((product) => (
              <div
                key={product.id}
                className="product-card"
                onMouseEnter={() => setHoveredProduct(product.id)}
                onMouseLeave={() => setHoveredProduct(null)}
              >
                <div className="product-icon">{product.icon}</div>
                <h3>{product.title}</h3>
                <div className="price">{product.price}</div>
                <p className="price-subtext">{product.priceSubtext}</p>
                <p>{product.description}</p>
                <button className="btn btn-primary" style={{ width: '100%' }}>
                  Learn More
                </button>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="features" id="features">
        <div className="section-container">
          <div className="section-header">
            <h2>See your whole business click into place</h2>
            <p>Comprehensive tools to manage every aspect of your business.</p>
          </div>
          <div className="features-grid">
            {features.map((feature) => (
              <div key={feature.id} className="feature-card">
                <h3>{feature.title}</h3>
                <p>{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Stats Section */}
      <section className="stats">
        <div className="section-container">
          <div className="stats-grid">
            {stats.map((stat) => (
              <div key={stat.id} className="stat-item">
                <h4>{stat.number}</h4>
                <p>{stat.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="cta">
        <div className="section-container">
          <h2>Ready to transform your business?</h2>
          <p>Join thousands of businesses already using Square to grow and succeed.</p>
          <button
            className="btn btn-light"
            style={{
              backgroundColor: 'white',
              color: '#6366f1',
              padding: '12px 40px',
              fontSize: '16px',
            }}
          >
            Start Your Free Trial
          </button>
        </div>
      </section>

      {/* Footer */}
      <footer>
        <div className="footer-content">
          {footerSections.map((section, index) => (
            <div key={index} className="footer-section">
              <h4>{section.title}</h4>
              {section.links.map((link, linkIndex) => (
                <a key={linkIndex} href="#">
                  {link}
                </a>
              ))}
            </div>
          ))}
        </div>
        <div className="footer-bottom">
          <p>&copy; 2026 Square, Inc. All rights reserved. | Privacy | Terms | Accessibility</p>
        </div>
      </footer>
    </div>
  );
}
